name: Build TWRP Recovery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7

    - name: Maximize Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo apt-get clean
        echo "Disk space freed"

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential ccache curl git gperf libxml2-utils make zip libssl-dev python3 python-is-python3

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize TWRP Source
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Skyzers"
        git config --global user.email "skyzers@example.com"
        ~/bin/repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
        ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd workspace
        git clone ${{ github.server_url }}/${{ github.repository }} device/samsung/a03

    - name: Forced Build Recovery
      run: |
        cd workspace
        export PATH=~/bin:$PATH
        
        # EXPORT FORCED FLAGS
        export ALLOW_MISSING_DEPENDENCIES=true
        export SOONG_ALLOW_MISSING_DEPENDENCIES=true
        export BUILD_BROKEN_MISSING_REQUIRED_MODULES=true
        export BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES=true
        export BUILD_BROKEN_DUP_RULES=true
        export BUILD_BROKEN_OUTSIDE_INCLUDE_PATHS=true

        source build/envsetup.sh

        # Auto-Fix / Hapus Modul Bermasalah (VTS & Hal Interface Bawaan)
        rm -rf hardware/interfaces/vts
        rm -rf test/vts
        find hardware/interfaces/ -type f -name "Android.bp" -exec grep -l "vts" {} + | xargs rm -f || true
        find vendor/qcom/opensource/interfaces/ -type f -name "Android.bp" -exec grep -l "vts" {} + | xargs rm -f || true

        # Auto-Patch Header libcutils
        mkdir -p system/core/libcutils/include/private
        find system/core -name "android_filesystem_config.h" -exec cp {} system/core/libcutils/include/private/ \; || true

        lunch twrp_a03-eng
        mka recoveryimage -j$(nproc --all)

    - name: Upload Recovery Artifact
      uses: actions/upload-artifact@v7
      with:
        name: TWRP_Galaxy_A03
        path: workspace/out/target/product/a03/recovery.img
